# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 450)
        MainWindow.setMinimumSize(QtCore.QSize(450, 450))
        MainWindow.setMaximumSize(QtCore.QSize(450, 450))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, -30, 251, 81))
        self.label.setMinimumSize(QtCore.QSize(81, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setGeometry(QtCore.QRect(170, 350, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Save.setFont(font)
        self.Save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"    width: 25px;\n"
"    height: 25px;\n"
"}")
        self.Save.setObjectName("Save")
        self.New_Scramble = QtWidgets.QPushButton(self.centralwidget)
        self.New_Scramble.setGeometry(QtCore.QRect(20, 110, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.New_Scramble.setFont(font)
        self.New_Scramble.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"    width: 25px;\n"
"    height: 25px;\n"
"}")
        self.New_Scramble.setObjectName("New_Scramble")
        self.Scramble_Output = QtWidgets.QLabel(self.centralwidget)
        self.Scramble_Output.setGeometry(QtCore.QRect(160, 110, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Scramble_Output.setFont(font)
        self.Scramble_Output.setAutoFillBackground(False)
        self.Scramble_Output.setStyleSheet("color: rgb(255, 255, 255);")
        self.Scramble_Output.setFrameShape(QtWidgets.QFrame.Box)
        self.Scramble_Output.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Scramble_Output.setText("")
        self.Scramble_Output.setObjectName("Scramble_Output")
        self.Timer_stopwatch = QtWidgets.QLabel(self.centralwidget)
        self.Timer_stopwatch.setGeometry(QtCore.QRect(180, 190, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Timer_stopwatch.setFont(font)
        self.Timer_stopwatch.setStyleSheet("color: rgb(255, 255, 255);")
        self.Timer_stopwatch.setObjectName("Timer_stopwatch")
        self.StartandStop = QtWidgets.QPushButton(self.centralwidget)
        self.StartandStop.setGeometry(QtCore.QRect(120, 290, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.StartandStop.setFont(font)
        self.StartandStop.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"    width: 25px;\n"
"    height: 25px;\n"
"}")
        self.StartandStop.setObjectName("StartandStop")
        self.Username = QtWidgets.QLineEdit(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(160, 50, 281, 31))
        self.Username.setStyleSheet("color: rgb(255, 255, 255);")
        self.Username.setObjectName("Username")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Rubix Cube Timer"))
        self.Save.setText(_translate("MainWindow", "Save Time"))
        self.New_Scramble.setText(_translate("MainWindow", "New Scramble"))
        self.Timer_stopwatch.setText(_translate("MainWindow", "00.00"))
        self.StartandStop.setText(_translate("MainWindow", "Start/Stop"))
        self.label_3.setText(_translate("MainWindow", "Enter User :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
